/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc_v5.view.funcionario;

import javax.swing.JOptionPane;
import projetotcc_v5.DAO.FuncionarioDAO;
import projetotcc_v5.modelo.Endereco;
import projetotcc_v5.modelo.Funcionario;

/**
 *
 * @author lab
 */
public class DFrmAltFunc extends javax.swing.JDialog {

    /**
     * Creates new form DFrmAltFunc
     */
    public DFrmAltFunc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        try {
            javax.swing.text.MaskFormatter msk = new javax.swing.text.MaskFormatter("###.###.###-##");
            txtCpf = new javax.swing.JFormattedTextField(msk);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        jLabel6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter msk = new javax.swing.text.MaskFormatter("########");
            txtCpf = new javax.swing.JFormattedTextField(msk);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnexcluir = new javax.swing.JButton();
        txtTel = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter msk = new javax.swing.text.MaskFormatter("(##)####-####");
            txtTel = new javax.swing.JFormattedTextField(msk);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        jLabel5 = new javax.swing.JLabel();
        btnalterar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtdtnasc = new javax.swing.JFormattedTextField();
        txtcomplemento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcep = new javax.swing.JFormattedTextField();
        lblcep = new javax.swing.JLabel();
        lblcod = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtDtCad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Pesquisa de Funcionário");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setToolTipText("11 dígitos no total");
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 110, 30));

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel6.setText("Número");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 113, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, -1));

        jLabel12.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel12.setText("Funcionário");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel7.setText("Data de Nascimento");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 161, -1, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel2.setText("Nome Funcionário");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 99, -1, -1));

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel9.setText("Endereço");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(txtLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 100, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel3.setText("Bairro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel8.setText("Telefone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 161, -1, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 127, 300, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setText("CPF");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        btnexcluir.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));

        txtTel.setToolTipText("");
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
        });
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 189, 113, -1));

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel5.setText("Cidade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        btnalterar.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel10.setText("Rua");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 370, -1));

        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, -1));

        jLabel11.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel11.setText("Estado");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        try {
            txtdtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdtnasc.setText("");
        getContentPane().add(txtdtnasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 140, -1));
        getContentPane().add(txtcomplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 250, -1));

        jLabel14.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel14.setText("Complemento");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 110, -1));

        lblcep.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        lblcep.setText("CEP");
        getContentPane().add(lblcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        lblcod.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        lblcod.setText("ID");
        lblcod.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblcodAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel15.setText("Data de Cadastro");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));
        getContentPane().add(txtDtCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 150, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        Funcionario f = new Funcionario();
        FuncionarioDAO fdao = new FuncionarioDAO();
        int r = JOptionPane.showConfirmDialog(null, "Voce realmente deseja apagar este registro?");
        if (r == 0){
            f.setIdFuncionario(Integer.parseInt(lblcod.getText()));
            fdao.remover(f);
            txtNome.setText("");
            txtCpf.setText("");
            txtTel.setText("");
            txtestado.setText("");
            txtCidade.setText("");
            txtBairro.setText("");
            txtRua.setText("");
            txtLogradouro.setText("");
            txtcep.setText("");
            txtcomplemento.setText("");
            txtDtCad.setText("");
            txtdtnasc.setText("");
        }
        
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed

    }//GEN-LAST:event_txtTelKeyPressed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
         int alt = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar este cadastro?");
        Funcionario f = new Funcionario();
        FuncionarioDAO fdao = new FuncionarioDAO();
        Endereco e = new Endereco();
        if (alt == 0) {
            f.setNome(txtNome.getText());
            f.setCpf(txtCpf.getText());
            f.setTelefone(txtTel.getText());
            f.setDataNascimento(txtdtnasc.getText());
            e.setUnidadeFederal(txtestado.getText());
            e.setCidade(txtCidade.getText());
            e.setBairro(txtBairro.getText());
            e.setRua(txtRua.getText());
            e.setLogradouroNum(Integer.parseInt(txtLogradouro.getText()));
            e.setCep(txtcep.getText());
            e.setComplemento(txtcomplemento.getText());

            fdao.alterar(f, e);
            JOptionPane.showMessageDialog(null, "Fornecedor alterado com sucesso");
            txtNome.setText("");
            txtCpf.setText("");
            txtTel.setText("");
            txtestado.setText("");
            txtCidade.setText("");
            txtBairro.setText("");
            txtRua.setText("");
            txtLogradouro.setText("");
            txtcep.setText("");
            txtcomplemento.setText("");
            txtDtCad.setText("");
            txtdtnasc.setText("");
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void lblcodAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblcodAncestorAdded
        Funcionario f = new Funcionario();
        Endereco e = new Endereco();
        FuncionarioDAO fdao = new FuncionarioDAO();
        try{
            fdao.pesquisar(f, e, "idFuncionario", lblcod.getText());
            txtNome.setText("" + f.getNome());
            txtCpf.setText("" + f.getCpf());
            txtDtCad.setText("" + f.getDataCadastro());
            txtTel.setText("" + f.getTelefone());
            txtestado.setText("" + e.getUnidadeFederal());
            txtBairro.setText("" + e.getBairro());
            txtCidade.setText("" + e.getCidade());
            txtLogradouro.setText("" + e.getLogradouroNum());
            txtRua.setText("" + e.getRua());
            txtcep.setText("" + e.getCep());
            txtcomplemento.setText("" + e.getComplemento());
            txtdtnasc.setText(""+ f.getDataNascimento());
        } catch (Exception erro){
            throw new RuntimeException(erro);
        }
    }//GEN-LAST:event_lblcodAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DFrmAltFunc dialog = new DFrmAltFunc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnalterar;
    public javax.swing.JButton btnexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblcep;
    public javax.swing.JLabel lblcod;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtDtCad;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTel;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JFormattedTextField txtdtnasc;
    private javax.swing.JTextField txtestado;
    // End of variables declaration//GEN-END:variables
}
