/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc_v5.view.funcionario;

import projetotcc_v5.view.*;
import javax.swing.table.DefaultTableModel;
import projetotcc_v5.DAO.ClienteDAO;
import projetotcc_v5.DAO.FuncionarioDAO;
import projetotcc_v5.modelo.Cliente;
import projetotcc_v5.modelo.Funcionario;

/**
 *
 * @author matheus
 */
public class DFrmGerenciamentoFuncionario extends javax.swing.JDialog {

    /**
     * Creates new form DFrmGerenciamentoCliente1
     */
    public DFrmGerenciamentoFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfunc = new javax.swing.JTable();
        cbpesfun = new javax.swing.JComboBox<>();
        txtpes = new javax.swing.JTextField();
        btncadfun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblfunc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblfunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "CPF", "Data Cadastro", "Data Nascimento", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblfunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblfuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblfunc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, 784, 95));

        cbpesfun.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbpesfun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "CPF" }));
        cbpesfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpesfunActionPerformed(evt);
            }
        });
        getContentPane().add(cbpesfun, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 73, 89, -1));

        txtpes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtpes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesKeyReleased(evt);
            }
        });
        getContentPane().add(txtpes, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 73, 578, -1));

        btncadfun.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btncadfun.setText("Cadastrar");
        btncadfun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncadfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadfunActionPerformed(evt);
            }
        });
        getContentPane().add(btncadfun, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 136, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gerenciamento de Funcionários");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 11, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblfuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblfuncMouseClicked
        if (evt.getClickCount() == 1) {
            DFrmAltFunc f = new DFrmAltFunc(null, rootPaneCheckingEnabled);

            f.lblcod.setText(tblfunc.getValueAt(tblfunc.getSelectedRow(), 0).toString());
            f.setVisible(true);

        }
    }//GEN-LAST:event_tblfuncMouseClicked

    private void txtpesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesKeyReleased
        FuncionarioDAO fdao = new FuncionarioDAO();
        Funcionario f = new Funcionario();
       
        java.util.List<Funcionario> funcionarios = fdao.listar(cbpesfun.getSelectedItem().toString(), txtpes.getText());
        DefaultTableModel model = (DefaultTableModel) tblfunc.getModel();
        model.setNumRows(0);
        for (Funcionario fun : funcionarios) {
            model.addRow(new Object[]{
                fun.getIdFuncionario(),
                fun.getNome(),
                fun.getCpf(),
                fun.getDataCadastro(),
                fun.getDataNascimento(),
                fun.getTelefone(),
            });

        }
    }//GEN-LAST:event_txtpesKeyReleased

    private void btncadfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadfunActionPerformed
        new DFrmAltFunc(null, rootPaneCheckingEnabled).setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btncadfunActionPerformed

    private void cbpesfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpesfunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpesfunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmGerenciamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmGerenciamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmGerenciamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmGerenciamentoFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DFrmGerenciamentoFuncionario dialog = new DFrmGerenciamentoFuncionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadfun;
    private javax.swing.JComboBox<String> cbpesfun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblfunc;
    private javax.swing.JTextField txtpes;
    // End of variables declaration//GEN-END:variables
}
