/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetotcc_v5.view.veiculo;

import com.sun.glass.events.KeyEvent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import projetotcc_v5.DAO.CarroDAO;
import projetotcc_v5.modelo.Carro;

/**
 *
 * @author lab
 */
public class DFrmCadVeiculo extends javax.swing.JDialog {

    /** Creates new form DFrmCadVeiculo */
    public DFrmCadVeiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlaca = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter msk = new javax.swing.text.MaskFormatter("???-####");
            txtPlaca = new javax.swing.JFormattedTextField(msk);
        }catch(Exception e){
            throw new RuntimeException(e);
        }
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        btnCad = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDetLav = new javax.swing.JTextField();
        txtNomeVeiculo = new javax.swing.JFormattedTextField();
        lblId = new javax.swing.JLabel();
        txtVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaObs = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPlaca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 226, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel2.setText("Placa do Veículo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Veículo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 11, -1, -1));

        txtCor.setToolTipText("");
        txtCor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorKeyPressed(evt);
            }
        });
        getContentPane().add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, 113, -1));

        btnCad.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btnCad.setText("Cadastrar");
        btnCad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });
        getContentPane().add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 334, -1, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setText("Nome do Veículo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 101, -1, -1));

        jLabel7.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel7.setText("Observações");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel8.setText("Cor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel11.setText("Detalhes de Lavagem");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, -1, -1));

        txtDetLav.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtDetLav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, 120, -1));

        txtNomeVeiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNomeVeiculo.setToolTipText("11 dígitos no total");
        getContentPane().add(txtNomeVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 129, 113, -1));

        lblId.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        lblId.setText("Cliente");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        txtVoltar.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        txtVoltar.setText("Voltar");
        txtVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(txtVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 334, -1, -1));

        areaObs.setColumns(20);
        areaObs.setRows(5);
        areaObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                areaObsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(areaObs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 181, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorKeyPressed

    }//GEN-LAST:event_txtCorKeyPressed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        Carro c = new Carro();

        c.setPlacaVeiculo(txtPlaca.getText());
        c.setNomeVeiculo(txtNomeVeiculo.getText());
        c.setCorVeiculo(txtCor.getText());
        c.setObservacoes(areaObs.getText());
        c.setDetalhesLavagem(txtDetLav.getText());
        c.setIdClienteFK(Integer.parseInt(lblId.getText()));

        CarroDAO cdao = new CarroDAO();
        cdao.adicionar(c);

        JOptionPane.showMessageDialog(null, "Carro cadastrado com sucesso.");

        txtPlaca.setText("");
        txtNomeVeiculo.setText("");
        txtCor.setText("");
        areaObs.setText("");
        txtDetLav.setText("");
        txtPlaca.requestFocus();
    }//GEN-LAST:event_btnCadActionPerformed

    private void txtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_txtVoltarActionPerformed

    private void areaObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaObsKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB){
            txtDetLav.requestFocus();
        }
    }//GEN-LAST:event_areaObsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmCadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmCadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmCadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmCadVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DFrmCadVeiculo dialog = new DFrmCadVeiculo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaObs;
    private javax.swing.JButton btnCad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblId;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtDetLav;
    private javax.swing.JFormattedTextField txtNomeVeiculo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JButton txtVoltar;
    // End of variables declaration//GEN-END:variables

}
