/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc_v5.view.produto;

import projetotcc_v5.view.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import projetotcc_v5.DAO.FornecedorDAO;
import projetotcc_v5.DAO.ProdutoEstoqueDAO;
import projetotcc_v5.modelo.Fornecedor;
import projetotcc_v5.modelo.ProdutoEstoque;

/**
 *
 * @author Liege
 */
public class DFrmAltProd extends javax.swing.JDialog {

    /**
     * Creates new form DFrmAltProd
     */
    public DFrmAltProd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtqtd = new javax.swing.JTextField();
        txtnomeprod = new javax.swing.JTextField();
        txtcodbarras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdtentrada = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        cbforn = new javax.swing.JComboBox<>();
        btnalterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnexcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel5.setText("Data de Entrada");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 239, -1, -1));

        txtqtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdActionPerformed(evt);
            }
        });
        getContentPane().add(txtqtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 84, 90, -1));
        getContentPane().add(txtnomeprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 122, 90, -1));
        getContentPane().add(txtcodbarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 160, 90, -1));

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel6.setText("Fornecedor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 201, -1, -1));

        try {
            txtdtentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdtentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdtentradaActionPerformed(evt);
            }
        });
        getContentPane().add(txtdtentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 239, 90, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Alterar Produto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 11, -1, -1));

        cbforn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbforn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbfornAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(cbforn, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 198, 90, -1));

        btnalterar.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        btnalterar.setText("Alterar");
        btnalterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel2.setText("Quantidade");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 84, -1, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel3.setText("Nome produto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 122, -1, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setText("Código de Barras");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 160, -1, -1));

        btnexcluir.setFont(new java.awt.Font("Elephant", 0, 11)); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 300, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtqtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdActionPerformed

    private void txtdtentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdtentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdtentradaActionPerformed

    private void cbfornAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbfornAncestorAdded
        FornecedorDAO fdao = new FornecedorDAO();
        List<Fornecedor> fornecedores = fdao.listar2();
        DefaultComboBoxModel model=(DefaultComboBoxModel)cbforn.getModel();
        model.removeAllElements();
        for (Fornecedor f:fornecedores) {
            model.addElement(f.getNomeFantasia());
        }
    }//GEN-LAST:event_cbfornAncestorAdded

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        
        
        ProdutoEstoque pe = new ProdutoEstoque();
        ProdutoEstoqueDAO pedao = new ProdutoEstoqueDAO();
        Fornecedor f = new Fornecedor();
        pe.setNomeProd(txtnomeprod.getText());
        pe.setCodBarras(txtcodbarras.getText());

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate d = LocalDate.parse(txtdtentrada.getText(), formato);
        pe.setDataEntrada(d.toString());

        pe.setQtde(Integer.parseInt(txtqtd.getText()));
        f.setNomeFantasia(cbforn.getSelectedItem().toString());
        pe.setFornecedor(f);
        pedao.alterar(pe,f);
        JOptionPane.showMessageDialog(null, "Produto Alerado com Sucesso");
    }//GEN-LAST:event_btnalterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmAltProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmAltProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmAltProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmAltProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DFrmAltProd dialog = new DFrmAltProd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JComboBox<String> cbforn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtcodbarras;
    private javax.swing.JFormattedTextField txtdtentrada;
    private javax.swing.JTextField txtnomeprod;
    private javax.swing.JTextField txtqtd;
    // End of variables declaration//GEN-END:variables
}
