/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc_v5.view.produto;

import projetotcc_v5.view.*;
import javax.swing.table.DefaultTableModel;
import projetotcc_v5.DAO.ProdutoEstoqueDAO;
import projetotcc_v5.modelo.ProdutoEstoque;

/**
 *
 * @author Administrador
 */
public class FrmGerenciamentoProduto extends javax.swing.JFrame {

    /**
     * Creates new form FrmGerenciamentoProduto
     */
    public FrmGerenciamentoProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfunc = new javax.swing.JTable();
        cbpesprod = new javax.swing.JComboBox<>();
        txtpes = new javax.swing.JTextField();
        btncadfun = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gerenciamento de Produtos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 11, -1, -1));

        tblfunc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblfunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Qtd", "Data Entrada", "Empresa", "CNPJ", "Data Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblfunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblfuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblfunc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 728, 95));

        cbpesprod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbpesprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produto", "Fornecedor" }));
        cbpesprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpesprodActionPerformed(evt);
            }
        });
        getContentPane().add(cbpesprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 75, 89, -1));

        txtpes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtpes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesKeyReleased(evt);
            }
        });
        getContentPane().add(txtpes, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 75, 522, -1));

        btncadfun.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btncadfun.setText("Cadastrar");
        btncadfun.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncadfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadfunActionPerformed(evt);
            }
        });
        getContentPane().add(btncadfun, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 238, 136, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblfuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblfuncMouseClicked
        if (evt.getClickCount() == 1) {
            DFrmAltFunc f = new DFrmAltFunc(null, rootPaneCheckingEnabled);

            f.lblcod.setText(tblfunc.getValueAt(tblfunc.getSelectedRow(), 0).toString());
            f.setVisible(true);

        }
    }//GEN-LAST:event_tblfuncMouseClicked

    private void cbpesprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpesprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpesprodActionPerformed

    private void txtpesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesKeyReleased
        ProdutoEstoqueDAO pdao = new ProdutoEstoqueDAO();
        ProdutoEstoque p = new ProdutoEstoque();
        String campo = null;
        if (cbpesprod.getSelectedIndex() == 0) {
            campo = "Produto";
        } else if (cbpesprod.getSelectedIndex() == 1) {
            campo = "nomeFantasia";
        }

        java.util.List<ProdutoEstoque> produtos = pdao.listaProduto(p,"nome", txtpes.getText());
        DefaultTableModel model = (DefaultTableModel) tblfunc.getModel();
        model.setNumRows(0);
        for (ProdutoEstoque ps : produtos) {
            model.addRow(new Object[]{
                ps.getIdProdEstoque(),
                ps.getNomeProd(),
                ps.getQtde(),
                ps.getDataEntrada(),
                ps.getFornecedor().getNomeFantasia(),
                ps.getFornecedor().getCnpj(),
                ps.getFornecedor().getDataCadastro()
            });

        }
    }//GEN-LAST:event_txtpesKeyReleased

    private void btncadfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadfunActionPerformed
        new DFrmAltProd(null, rootPaneCheckingEnabled).setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btncadfunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciamentoProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadfun;
    private javax.swing.JComboBox<String> cbpesprod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblfunc;
    private javax.swing.JTextField txtpes;
    // End of variables declaration//GEN-END:variables
}
