/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc_v5.view.cliente;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetotcc_v5.DAO.CarroDAO;
import projetotcc_v5.DAO.ClienteDAO;
import projetotcc_v5.modelo.Carro;
import projetotcc_v5.modelo.Cliente;
import projetotcc_v5.view.veiculo.DFrmAltCarro;
import projetotcc_v5.view.veiculo.DFrmCadVeiculo;
import projetotcc_v5.view.veiculo.FrmCadVeiculo;

/**
 *
 * @author lab
 */
public class DFrmAltCliente extends javax.swing.JDialog {

    /**
     * Creates new form DFrmAltCliente
     */
    public DFrmAltCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnexcluir = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter msk = new javax.swing.text.MaskFormatter("(##)####-####");
            txtTel = new javax.swing.JFormattedTextField(msk);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        txtCel = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter msk = new javax.swing.text.MaskFormatter("(##)#####-####");
            txtCel = new javax.swing.JFormattedTextField(msk);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        txtCpf = new javax.swing.JFormattedTextField();
        lblid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcarros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtDtCad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();
        btncadVeiculo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel9.setText("Veículo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setText("CPF");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        btnexcluir.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btnexcluir.setText("Excluir");
        btnexcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        btnalterar.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btnalterar.setText("Alterar");
        btnalterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Alterar Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel7.setText("Celular");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel8.setText("Telefone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 226, -1));

        txtTel.setToolTipText("");
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
        });
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 113, -1));
        getContentPane().add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 113, -1));

        txtCpf.setToolTipText("11 dígitos no total");
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 113, -1));

        lblid.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        lblid.setText("Cliente");
        lblid.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblidAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 82, -1, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        tblcarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Placa do Veículo", "Nome do Veiculo", "Cor ", "Observações", "Detalhes de Lavagem", "Cliente"
            }
        ));
        tblcarros.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblcarrosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblcarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcarrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcarros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 430, 90));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel3.setText("Data de Cadastro");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));
        getContentPane().add(txtDtCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 130, -1));

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel5.setText("Data de Nascimento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, -1));

        btncadVeiculo.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btncadVeiculo.setText("Cadastrar Veículo");
        btncadVeiculo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadVeiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btncadVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 160, -1));

        jLabel10.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        Cliente c = new Cliente();
        int r = JOptionPane.showConfirmDialog(null, "Você realmente deseja remover este cadastro?");
        if(r == 0) {
            c.setIdCliente(Integer.parseInt(lblid.getText()));
            
            ClienteDAO cdao = new ClienteDAO();
            cdao.remover(c);
                txtNome.setText("");
                txtCpf.setText("");
                txtCel.setText("");
                txtTel.setText("");
                txtDtCad.setText("");
        }

        
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
        Cliente c = new Cliente();
        int r = JOptionPane.showConfirmDialog(null, "Você realmente deseja alterar este cadastro?");
        if(r == 0) {
            c.setIdCliente(Integer.parseInt(lblid.getText()));
            c.setNome(txtNome.getText());
            c.setCpf(txtCpf.getText());
            c.setTelefone(txtTel.getText());
            c.setCelular(txtCel.getText());
            c.setDataNascimento(txtDataNascimento.getText());

            ClienteDAO cdao = new ClienteDAO();
            cdao.alterar(c);
            JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso.");
            txtNome.setText("");
            txtCpf.setText("");
            txtCel.setText("");
            txtTel.setText("");
            txtDtCad.setText("");
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed

    }//GEN-LAST:event_txtTelKeyPressed

    private void lblidAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblidAncestorAdded
        Cliente c = new Cliente();
        ClienteDAO d = new ClienteDAO();
        try {
            d.pesquisar("idCliente", lblid.getText(), c);
            txtNome.setText(c.getNome());
            txtCpf.setText(c.getCpf());
            txtCel.setText(c.getCelular());
            txtTel.setText(c.getTelefone());
            txtDtCad.setText(""+c.getDtcadastro());
            txtDataNascimento.setText(""+ c.getDataNascimento());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_lblidAncestorAdded

    private void btncadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadVeiculoActionPerformed
       DFrmCadVeiculo v = new DFrmCadVeiculo(null, rootPaneCheckingEnabled);
       v.lblId.setText(lblid.getText());
       v.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btncadVeiculoActionPerformed

    private void tblcarrosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblcarrosAncestorAdded
    //listar a pesquisa
        CarroDAO d = new CarroDAO();
        List<Carro> carros = d.listar("idClienteFK", lblid.getText());
        DefaultTableModel model = (DefaultTableModel) tblcarros.getModel();
        model.setNumRows(0);
        for (Carro c : carros) {
            model.addRow(new Object[]{
                c.getIdCarro(),
                c.getPlacaVeiculo(),
                c.getNomeVeiculo(),
                c.getCorVeiculo(),
                c.getObservacoes(),
                c.getDetalhesLavagem(),
                c.getIdClienteFK()
            });

        }
    }//GEN-LAST:event_tblcarrosAncestorAdded

    private void tblcarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcarrosMouseClicked
        if (evt.getClickCount() == 1) {
            DFrmAltCarro f = new DFrmAltCarro(null, rootPaneCheckingEnabled);
            f.lblId.setText(tblcarros.getValueAt(tblcarros.getSelectedRow(),0).toString());
            f.setVisible(true);
           
        }
    }//GEN-LAST:event_tblcarrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmAltCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DFrmAltCliente dialog = new DFrmAltCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnalterar;
    private javax.swing.JButton btncadVeiculo;
    public javax.swing.JButton btnexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblid;
    private javax.swing.JTable tblcarros;
    private javax.swing.JTextField txtCel;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtDtCad;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
