/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc_v5.view.fornecedor;

import projetotcc_v5.view.*;
import javax.swing.JOptionPane;
import projetotcc_v5.DAO.FornecedorDAO;
import projetotcc_v5.DAO.FuncionarioDAO;
import projetotcc_v5.modelo.Endereco;
import projetotcc_v5.modelo.Fornecedor;
import projetotcc_v5.modelo.Funcionario;

/**
 *
 * @author lab
 */
public class DFrmAltFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public DFrmAltFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtcep = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JTextField();
        txtnum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtcnpj = new javax.swing.JFormattedTextField();
        txttel = new javax.swing.JTextField();
        lbltel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcomplemento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdatacadastro = new javax.swing.JFormattedTextField();
        lblcep = new javax.swing.JLabel();
        btnalterar = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        lblcod = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Número");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("Complemento");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 286, -1, -1));
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 260, 113, -1));

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 249, 110, -1));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 260, 113, -1));
        getContentPane().add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 313, 85, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Bairro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 221, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Cidade");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 229, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Rua");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 216, -1, -1));
        getContentPane().add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 260, 105, -1));

        txtestado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 311, 100, 20));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("CNPJ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Nome do Fornecedor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 226, -1));

        try {
            txtcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 85, 114, -1));
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, 112, -1));

        lbltel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbltel.setText("Telefone");
        getContentPane().add(lbltel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel1.setText("Alterar Fornecedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 11, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Estado");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 286, -1, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setText("Endereço");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        getContentPane().add(txtcomplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 313, 120, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Data Cadastro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 132, -1, -1));

        txtdatacadastro.setEditable(false);
        try {
            txtdatacadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatacadastro.setText("");
        getContentPane().add(txtdatacadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 155, 119, -1));

        lblcep.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblcep.setText("CEP");
        getContentPane().add(lblcep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, -1, -1));

        btnalterar.setText("Alterar");
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnalterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 353, -1, -1));

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 353, -1, -1));

        lblcod.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        lblcod.setText("ID");
        lblcod.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblcodAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
         int alt = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar este cadastro?");
        Fornecedor f = new Fornecedor();
        Endereco e = new Endereco();
        if (alt == 0) {
            f.setNomeFantasia(txtNome.getText());
            f.setCnpj(txtcnpj.getText());
            f.setTelefone(txttel.getText());
            e.setUnidadeFederal(txtestado.getText());
            e.setCidade(txtCidade.getText());
            e.setBairro(txtBairro.getText());
            e.setRua(txtRua.getText());
            e.setLogradouroNum(Integer.parseInt(txtnum.getText()));
            e.setCep(txtcep.getText());
            e.setComplemento(txtcomplemento.getText());
            FornecedorDAO fdao = new FornecedorDAO();

            fdao.alterar(f, e);
            JOptionPane.showMessageDialog(null, "Fornecedor alterado com sucesso");
            txtNome.setText("");
            txtcnpj.setText("");
            txttel.setText("");
            txtestado.setText("");
            txtCidade.setText("");
            txtBairro.setText("");
            txtRua.setText("");
            txtnum.setText("");
            txtcep.setText("");
            txtcomplemento.setText("");
            txtdatacadastro.setText("");
        }
    }//GEN-LAST:event_btnalterarActionPerformed

    private void lblcodAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblcodAncestorAdded
        Fornecedor f = new Fornecedor();
        Endereco e = new Endereco();
        FornecedorDAO fdao = new FornecedorDAO();
        try{
            fdao.pesquisar(f, e, "idFornecedor", lblcod.getText());
            txtNome.setText("" + f.getNomeFantasia());
            txtcnpj.setText("" + f.getCnpj());
            txtdatacadastro.setText("" + f.getDataCadastro());
            txttel.setText("" + f.getTelefone());
            txtestado.setText("" + e.getUnidadeFederal());
            txtBairro.setText("" + e.getBairro());
            txtCidade.setText("" + e.getCidade());
            txtnum.setText("" + e.getLogradouroNum());
            txtRua.setText("" + e.getRua());
            txtcep.setText("" + e.getCep());
            txtcomplemento.setText("" + e.getComplemento());
        } catch (Exception erro){
            throw new RuntimeException(erro);
        }
    }//GEN-LAST:event_lblcodAncestorAdded

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        Fornecedor f = new Fornecedor();
        FornecedorDAO fdao = new FornecedorDAO();
        int r = JOptionPane.showConfirmDialog(null, "Voce realmente deseja apagar este registro?");
        if (r == 0){
            f.setIdFornecedor(Integer.parseInt(lblcod.getText()));
            fdao.remover(f);
            txtNome.setText("");
            txtcnpj.setText("");
            txttel.setText("");
            txtestado.setText("");
            txtCidade.setText("");
            txtBairro.setText("");
            txtRua.setText("");
            txtnum.setText("");
            txtcep.setText("");
            txtcomplemento.setText("");
            txtdatacadastro.setText("");
        }
        
    }//GEN-LAST:event_btnexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmAltFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DFrmAltFornecedor dialog = new DFrmAltFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblcep;
    public javax.swing.JLabel lblcod;
    private javax.swing.JLabel lbltel;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JFormattedTextField txtcnpj;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JFormattedTextField txtdatacadastro;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
