/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotcc_v5.view;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import projetotcc_v5.DAO.FuncionarioDAO;
import projetotcc_v5.modelo.Login;

/**
 *
 * @author lab
 */
public class FrmDefinirSenha extends javax.swing.JDialog {

    /**
     * Creates new form FrmMudarSenha
     */
    public FrmDefinirSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCont = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        txtSenha = new JPasswordField();
        txtConfSenha = new javax.swing.JTextField();
        txtConfSenha = new JPasswordField();
        cbPer = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtRespPer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Definir Senha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Usuario");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel3.setText("Nova senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setText("Confirmar senha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btnCont.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        btnCont.setText("Confirmar");
        btnCont.setBorder(new javax.swing.border.SoftBevelBorder(0));
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });
        getContentPane().add(btnCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 333, -1, -1));

        txtLogin.setToolTipText("Nome atual do usuário");
        txtLogin.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 20));

        txtSenha.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 160, -1));

        txtConfSenha.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txtConfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, -1));

        cbPer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione....", "Qual o nome da sua professora da Sexta Serie?", "Qual seu prato favorito?", "Qual seu heroi favorito?", "Um momento marcante da sua vida?", "Qual lugar você gostaria de viajar?" }));
        cbPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerActionPerformed(evt);
            }
        });
        getContentPane().add(cbPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 231, -1, -1));

        jLabel5.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel5.setText("Resposta:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        txtRespPer.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txtRespPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 281, 160, -1));

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel6.setText("Pergunta Secreta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetotcc_v5/imagens/fundoTCC.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPerActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
        Login l = new Login();
        
        String campo = null;
        switch (cbPer.getSelectedIndex()) {
            case 0:
                campo = "Selecione....";
                break;
            case 1:
                campo = "Qual o nome da sua professora da Sexta Serie?";
                break;
            case 2:
                campo = "Qual seu prato favorito?";
                break;
            case 3:
                campo = "Qual seu heroi favorito?";
                break;
            case 4:
                campo = "Um momento marcante da sua vida?";
                break;
            case 5:
                campo = "Que lugar você gostaria de viajar?";
            default:
                break;
        }
        
        if(txtSenha.getText().equals(txtConfSenha.getText())){
            FuncionarioDAO fdao = new FuncionarioDAO();
            l.setLogin(txtLogin.getText());
            l.setSenha(txtSenha.getText());
            l.setPerguntaSecreta(campo);
            l.setRespostaSecreta(txtRespPer.getText());
            
            fdao.alterarSenhaPrimeiraVez(l);
            FrmLogin frmLogin = new FrmLogin();
            frmLogin.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos.");
        }
        
    }//GEN-LAST:event_btnContActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDefinirSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDefinirSenha dialog = new FrmDefinirSenha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCont;
    private javax.swing.JComboBox<String> cbPer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtConfSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtRespPer;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
